// ASCII portraits per archetype — 15-20 lines each
// Procedurally modified by flavor variables (gender, age, distinguishing feature)

const BASE_PORTRAITS = {
  'control-seeking': [
    '        ┌───────┐       ',
    '        │ ≡≡≡≡≡ │       ',
    '        │ ≡≡≡≡≡ │       ',
    '     ┌──┘       └──┐    ',
    '     │  ◉       ◉  │    ',
    '     │      ─┬─     │    ',
    '     │       │      │    ',
    '     │    ───┘      │    ',
    '     └──┐  ───  ┌──┘    ',
    '        │ │   │ │       ',
    '     ┌──┘ │   │ └──┐    ',
    '     │    │   │    │    ',
    '     │  ┌─┴───┴─┐  │    ',
    '     │  │CONTROL │  │    ',
    '     │  │ PANEL  │  │    ',
    '     └──┴───────┴──┘    ',
  ],
  'lonely': [
    '                         ',
    '        ╭───────╮       ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │  ·       ·  │    ',
    '     │              │    ',
    '     │      ╰╯      │    ',
    '     │              │    ',
    '     ╰──╮       ╭──╯    ',
    '        │       │       ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │              │    ',
    '     │              │    ',
    '     │   (empty)    │    ',
    '     ╰──────────────╯    ',
  ],
  'greedy': [
    '        ┌───────┐       ',
    '        │ $$$$$ │       ',
    '        │ $$$$$ │       ',
    '     ┌──┘       └──┐    ',
    '     │  $       $  │    ',
    '     │     ◄►      │    ',
    '     │              │    ',
    '     │   \\$$$$/    │    ',
    '     └──┐       ┌──┘    ',
    '        │ │   │ │       ',
    '     ┌──┘ │   │ └──┐    ',
    '     │  ┌─┘   └─┐  │    ',
    '     │  │ $ $ $ │  │    ',
    '     │  │  $$$  │  │    ',
    '     │  │ RATES │  │    ',
    '     └──┴───────┴──┘    ',
  ],
  'paranoid': [
    '       ┌─────────┐      ',
    '       │? ? ? ? ?│      ',
    '       │ ? ? ? ? │      ',
    '    ┌──┘         └──┐   ',
    '    │  ◎         ◎  │   ',
    '    │  │    ▲    │  │   ',
    '    │              │   ',
    '    │    ═══════    │   ',
    '    └──┐         ┌──┘   ',
    '       │ │     │ │      ',
    '    ┌──┘ │     │ └──┐   ',
    '    │    │     │    │   ',
    '    │  ┌─┴─────┴─┐  │   ',
    '    │  │ DO NOT  │  │   ',
    '    │  │  TOUCH  │  │   ',
    '    └──┴─────────┴──┘   ',
  ],
  'bored': [
    '        ╭───────╮       ',
    '        │ zzzzz │       ',
    '        │  zzzz │       ',
    '     ╭──┘       └──╮    ',
    '     │  ─       ─  │    ',
    '     │              │    ',
    '     │     ~~~      │    ',
    '     │              │    ',
    '     ╰──╮       ╭──╯    ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │     ╭╮       │    ',
    '     │    ╭╯│       │    ',
    '     │    │ ╰╮      │    ',
    '     │    phone     │    ',
    '     ╰──────────────╯    ',
  ],
  'ideological': [
    '       ┌─────────┐      ',
    '       │ ██ TRUTH│      ',
    '       │ ██ ONLY │      ',
    '    ┌──┘         └──┐   ',
    '    │  ●         ●  │   ',
    '    │      ──       │   ',
    '    │              │   ',
    '    │   ┌──────┐    │   ',
    '    └──┐│AGREE?│┌──┘   ',
    '       ││      ││      ',
    '    ┌──┘│      │└──┐   ',
    '    │   └──────┘    │   ',
    '    │  ┌─────────┐  │   ',
    '    │  │ pamphlet│  │   ',
    '    │  │  inside │  │   ',
    '    └──┴─────────┴──┘   ',
  ],
  'guilty': [
    '        ╭───────╮       ',
    '        │ ..... │       ',
    '        │ ..... │       ',
    '     ╭──┘       └──╮    ',
    '     │  ╲       ╱  │    ',
    '     │              │    ',
    '     │     ───      │    ',
    '     │    ╱         │    ',
    '     ╰──╮       ╭──╯    ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │ ╲            │    ',
    '     │  ╲           │    ',
    '     │   hands      │    ',
    '     │   wringing   │    ',
    '     ╰──────────────╯    ',
  ],
  'ambitious': [
    '        ┌───────┐       ',
    '        │ ★★★★★ │       ',
    '        │ ★★★★★ │       ',
    '     ┌──┘       └──┐    ',
    '     │  ◆       ◆  │    ',
    '     │      ▲       │    ',
    '     │              │    ',
    '     │    ╱────╲    │    ',
    '     └──┐       ┌──┘    ',
    '        │ │   │ │       ',
    '     ┌──┘ │   │ └──┐    ',
    '     │  ╔═╧═══╧═╗  │    ',
    '     │  ║ BEST  ║  │    ',
    '     │  ║  AT   ║  │    ',
    '     │  ║ THIS  ║  │    ',
    '     └──╚═══════╝──┘    ',
  ],
  'burned-out': [
    '        ╭───────╮       ',
    '        │ ░░░░░ │       ',
    '        │ ░░░░░ │       ',
    '     ╭──┘       └──╮    ',
    '     │  ─       ─  │    ',
    '     │  ╷       ╷  │    ',
    '     │              │    ',
    '     │    ─────     │    ',
    '     ╰──╮       ╭──╯    ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │    ☕        │    ',
    '     │   ╭───╮      │    ',
    '     │   │5th│      │    ',
    '     │   │cup│      │    ',
    '     ╰──────────────╯    ',
  ],
  'suspicious': [
    '       ┌─────────┐      ',
    '       │ ▓▓▓▓▓▓▓│      ',
    '       │ ▓▓▓▓▓▓▓│      ',
    '    ┌──┘         └──┐   ',
    '    │  ▬         ▬  │   ',
    '    │  ╲    ▲    ╱  │   ',
    '    │              │   ',
    '    │    ──────     │   ',
    '    └──┐         ┌──┘   ',
    '       │ │     │ │      ',
    '    ┌──┘ │     │ └──┐   ',
    '    │   ┌┘     └┐   │   ',
    '    │  ┌┴───────┴┐  │   ',
    '    │  │clipboard│  │   ',
    '    │  │ + notes │  │   ',
    '    └──┴─────────┴──┘   ',
  ],
  'empathetic': [
    '        ╭───────╮       ',
    '        │ ~~~~~ │       ',
    '        │ ~~~~~ │       ',
    '     ╭──┘       └──╮    ',
    '     │  ◠       ◠  │    ',
    '     │              │    ',
    '     │      ◡       │    ',
    '     │              │    ',
    '     ╰──╮       ╭──╯    ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │   ╭───╮      │    ',
    '     │   │ ♥ │      │    ',
    '     │   ╰───╯      │    ',
    '     │   (open)     │    ',
    '     ╰──────────────╯    ',
  ],
  'corrupt': [
    '       ┌─────────┐      ',
    '       │ ▓░▓░▓░▓│      ',
    '       │ ░▓░▓░▓░│      ',
    '    ┌──┘         └──┐   ',
    '    │  ◉    │    ◉  │   ',
    '    │       │       │   ',
    '    │    ╱──╯──╲    │   ',
    '    │   ╱       ╲   │   ',
    '    └──┐         ┌──┘   ',
    '       │ │     │ │      ',
    '    ┌──┘ │     │ └──┐   ',
    '    │  ╔═╧═════╧═╗  │   ',
    '    │  ║ NOTHING ║  │   ',
    '    │  ║ TO SEE  ║  │   ',
    '    │  ║  HERE   ║  │   ',
    '    └──╚═════════╝──┘   ',
  ],
}

// Recurring character portraits — distinct from archetypes
const RECURRING_PORTRAITS = {
  'rosa': [
    '        ╭───────╮       ',
    '        │ ∿∿∿∿∿ │       ',
    '        │∿∿∿∿∿∿∿│       ',
    '     ╭──┘       └──╮    ',
    '     │  ◠       ◠  │    ',
    '     │              │    ',
    '     │      ◡       │    ',
    '     │    ╱   ╲     │    ',
    '     ╰──╮       ╭──╯    ',
    '        │ ╲   ╱ │       ',
    '     ╭──┘  ╲ ╱  └──╮    ',
    '     │   ╭──┴──╮    │    ',
    '     │   │scarf│    │    ',
    '     │   ╰─────╯    │    ',
    '     │    Rosa      │    ',
    '     ╰──────────────╯    ',
  ],
  'agent_demir': [
    '       ┌─────────┐      ',
    '       │ ═══════ │      ',
    '       │ΞΞΞΞΞΞΞΞΞ│      ',
    '    ┌──┘         └──┐   ',
    '    │  ▬         ▬  │   ',
    '    │      ─┬─      │   ',
    '    │       │       │   ',
    '    │    ═══╪═══    │   ',
    '    └──┐         ┌──┘   ',
    '       │ │     │ │      ',
    '    ┌──┘ │     │ └──┐   ',
    '    │  ╔═╧═════╧═╗  │   ',
    '    │  ║  BADGE  ║  │   ',
    '    │  ║ ★ ICE ★ ║  │   ',
    '    │  ║  #4471  ║  │   ',
    '    └──╚═════════╝──┘   ',
  ],
  'marcus': [
    '        ╭───────╮       ',
    '        │▓▓▓▓▓▓▓│       ',
    '        │▓ CAP ▓│       ',
    '     ╭──┘       └──╮    ',
    '     │  ◉       ◉  │    ',
    '     │              │    ',
    '     │    ╱───╲     │    ',
    '     │              │    ',
    '     ╰──╮       ╭──╯    ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │   ╭─────╮    │    ',
    '     │   │ hah │    │    ',
    '     │   │ hah │    │    ',
    '     │   ╰─────╯    │    ',
    '     ╰──────────────╯    ',
  ],
  'elena': [
    '        ╭───────╮       ',
    '        │ ───── │       ',
    '        │ ───── │       ',
    '     ╭──┘       └──╮    ',
    '     │  ◆       ◆  │    ',
    '     │              │    ',
    '     │     ───      │    ',
    '     │              │    ',
    '     ╰──╮       ╭──╯    ',
    '        │       │       ',
    '     ╭──┘       └──╮    ',
    '     │   ┌─────┐    │    ',
    '     │   │watch│    │    ',
    '     │   │ ing │    │    ',
    '     │   └─────┘    │    ',
    '     ╰──────────────╯    ',
  ],
  'the_handler': [
    '       ┌─────────┐      ',
    '       │ ░░░░░░░ │      ',
    '       │ ░░░░░░░ │      ',
    '    ┌──┘    ░    └──┐   ',
    '    │  ■    ░    ■  │   ',
    '    │       ░       │   ',
    '    │    ───░───    │   ',
    '    │       ░       │   ',
    '    └──┐    ░    ┌──┘   ',
    '       │ │  ░  │ │      ',
    '    ┌──┘ │  ░  │ └──┐   ',
    '    │    │  ░  │    │   ',
    '    │  ╔═╧══░══╧═╗  │   ',
    '    │  ║ BURNER  ║  │   ',
    '    │  ║  PHONE  ║  │   ',
    '    └──╚═════════╝──┘   ',
  ],
}

// Flavor modifications — procedurally modify portrait based on NPC flavor variables
const FLAVOR_MODS = {
  hat: { line: 1, replacements: { '≡≡≡≡≡': '▓HAT▓', 'zzzzz': '▓HAT▓', '.....': '▓HAT▓', '~~~~~': '▓HAT▓', '░░░░░': '▓HAT▓', '★★★★★': '▓HAT▓', '$$$$$': '▓HAT▓' } },
  glasses: { line: 4, replacements: { '◉': '⊙', '●': '⊙', '◆': '⊙', '◠': '⊙', '·': '⊙', '─': '⊙', '▬': '⊙', '◎': '⊙', '■': '⊙' } },
  scar: { line: 5, append: '/' },
  beard: { line: 7, replacements: { '───┘': '╥╥╥┘', '───': '╥╥╥', '╰╯': '╥╥╥', '~~~': '╥╥╥' } },
}

function applyFlavor(lines, flavor) {
  if (!flavor || !lines) return lines
  const result = [...lines]
  for (const [key, mod] of Object.entries(FLAVOR_MODS)) {
    if (!flavor[key]) continue
    if (mod.replacements && mod.line < result.length) {
      let line = result[mod.line]
      for (const [from, to] of Object.entries(mod.replacements)) {
        line = line.replace(from, to)
      }
      result[mod.line] = line
    }
  }
  return result
}

/**
 * Get ASCII portrait for an NPC by archetype ID
 * @param {string} archetypeId - The archetype ID
 * @param {object} [flavor] - Optional flavor modifiers { hat, glasses, scar, beard }
 * @returns {string[]} Array of portrait lines
 */
export function getPortrait(archetypeId, flavor) {
  const base = BASE_PORTRAITS[archetypeId] || BASE_PORTRAITS['suspicious']
  return applyFlavor(base, flavor)
}

/**
 * Get ASCII portrait for a recurring character
 * @param {string} characterId - The recurring character ID
 * @returns {string[]} Array of portrait lines
 */
export function getRecurringPortrait(characterId) {
  return RECURRING_PORTRAITS[characterId] || null
}

export { BASE_PORTRAITS, RECURRING_PORTRAITS }
